name: "Github Actions Test"
env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: pip install python-telegram-bot
      - name: Run python script
        run: python test.py
        