name: "Github Actions Test"

on:
  push:
  
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install 
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python script
        run: python test.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}