name: "Github Actions Test"

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: pip install python-telegram-bot
      - name: Run python script
        run: python test.py
        